### ISSUE TITLE
AnyDesk Client Application customized for Linux and macOS.

### ISSUE THREAD

**Issue by homebrewtainy** [glpi-project/glpi-agent#63]
### Documentation

Yes, I read it

### Professional support

I still have but want a public following to inform the community

### Is your feature request related to a problem?

Hi @g-bougard,

As stated in the Issue #59 (and solved for MS-Windows), ultimately Linux and Apple macOS presents a specific directory for custom installations of the customized AnyDesk Client Application, with this file tree :

On Linux (rhel 8.5 RPM modified installation) :
```
[homebrewtainy@homebrewtainy-dev ~]# ls -alZ /etc/any*
/etc/anydesk:
total 24
drwxr-xr-x.   2 root root system_u:object_r:etc_t:s0    73  6 févr. 15:10 .
drwxr-xr-x. 155 root root system_u:object_r:etc_t:s0 12288  6 févr. 15:10 ..
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0     0  6 févr. 15:10 connection_trace.txt
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0  2762  6 févr. 15:10 service.conf
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0   519  6 févr. 15:11 system.conf

/etc/anydesk_ad_########:
total 24
drwxr-xr-x.   2 root root system_u:object_r:etc_t:s0    73  6 févr. 15:41 .
drwxr-xr-x. 155 root root system_u:object_r:etc_t:s0 12288  6 févr. 15:41 ..
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0     0  6 févr. 15:41 connection_trace.txt
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0  2762  6 févr. 15:41 service.conf
-rw-r--r--.   1 root root system_u:object_r:etc_t:s0   531  6 févr. 15:42 system.conf
[homebrewtainy@homebrewtainy-dev ~]#
```
On macOS (Big Sur DMG installation) :

```
homebrewtainy@Mac-de-homebrewtainy ~ % ls -al /etc/anydesk_ad_########
total 32
drwxr-xr-x   8 root  staff   256  6 fév 17:11 .
drwxr-xr-x  86 root  wheel  2752  6 fév 17:39 ..
drwx------   2 root  staff    64  6 fév 17:11 AnyDesk
-rw-rw-r--   1 root  staff   182  6 fév 17:22 connection_trace.txt
drwx------   2 root  staff    64  6 fév 17:11 incoming
-rw-rw-r--   1 root  staff  2952  6 fév 17:22 service.conf
-rw-rw-r--   1 root  staff   512  6 fév 18:15 system.conf
-rw-r--r--   1 root  staff   229  6 fév 17:11 user.conf
homebrewtainy@Mac-de-homebrewtainy ~ %
```

### Expected behavior

Here is the information to complete the possible improvement of the GLPI-Agent Remote Management module.

### Alternatives you've considered

Thank you for your attention.

Regards.

**Comment by g-bougard** [comment]
Hi @homebrewtainy 
I just pushed in cd98a4bf7 an update which should make the job.

**Comment by homebrewtainy** [comment]
Hi @g-bougard,

Tested this late afternoon with success on Linux VMware-VM (AlmaLinux el 8.5) and macOS VMware-VM (Big Sur) !!

GLPI Agent 1.2-gitdd04d55d + https://github.com/glpi-project/glpi-agent/commit/cd98a4bf70c3f7460cb8430c6cee5cca8d4afa1a  /  10.0.0-dev (still not RC1)

Thanks for the improvement :-)

**Comment by g-bougard** [comment]
Thank you for your feedback ;-)
