### ISSUE TITLE
Adding snom desk phones to SNMP discovery

### ISSUE THREAD

**Issue by venator42** [glpi-project/glpi-agent#840]
Right now, the phones get discovered by an agent and are imported as "Unmanaged assets". There is no information beside IP and MAC. It would be great If they would be linked into the phones category right away and we get some additional info like firmware version.

Is it possible, to add snom desk phones to the SNMP discovery / NetInventory?

Unfortunately the phones only support SNMP-GET, so snmpwalk isn't working.

You can get the OIDs here: https://service.snom.com/display/wiki/How+to+setup+SNMP

I already tried to get it working by editing sysobject.ids. However, you need the sysObjectID and it seems the phone doesnt have that. 

If I execute `snmpget -v1 -c public 192.168.100.41 1.3.6.1.2.1.1.2.0` I don't get a value. 

I also tried to discover it manually without success: `sudo glpi-netdiscovery --host 192.168.100.41 --debug --v1 --community public --file /tmp/snom-snmpwalk`

The command returns:
```
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: success
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```
The file snom-snmpwalk contains: `1.3.6.1.2.1.7526.2.4 = STRING: "Firmware"` (I tried to simulate a walkfile)

**Comment by g-bougard** [comment]
Hi @venator42 

that snmp policy is really weird. Why do they not support standard snmp OIDs ? I can understand having a security option, enabled by default, to filter snmp access. But snmp standard supports security models they should have implemented.

And that page reports only few OIDs. I'm really not sure this can help. For example, I don't see how to get the exact model, unless extracting it from the firmware string, but is this even reliable ?

Anyway, I tried to create a dedicated MibSupport module: [Snom.zip](https://github.com/user-attachments/files/18606876/Snom.zip)

You can extract the Snom.pm module into the lib/GLPI/Agent/SNMP/MibSupport folder of your scanning agent. This module will check for a Snom private OID and then will report at least TYPE as NETWORKING (PHONE is not really supported here), MANUFACTURER, MODEL and FIRMWARE. Model and firmware version will be extracted from the known firmware oid.

You will have to enable rule to import and update by Mac Address in GLPI.

Can you give this module a try and tell us how it works ?

**Comment by venator42** [comment]
Unfortunately it does not work. I tested it with two different agents.

Agent 1 is installed via AppImage. I unzipped the file to `/usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport` and even restarted the systemd-service.

Agent 2 is compiled manually and I unzipped to `lib/GLPI/Agent/SNMP/MibSupport` in the build directory and run the agent from `bin/glpi-netdiscovery`, but no success.

The command returns
```
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
```
If i start the discovery in GLPI the devices are discovered as Unmanaged Assets again and Firmware, Manufacturer and Model are missing. Did I miss something on the agent side?

**Comment by g-bougard** [comment]
Hi @venator42 

for AppImage, this is normal, it uses embedded folders and won't look into the folder you expected.

For the other, "missing response" is self-explanatory: that agent don't have access to the device or device didn't trust it, maybe because of missing or wrong credentials.

**Comment by g-bougard** [comment]
Hi @venator42 

have you managed to test and validate the update I proposed ? Without you feedback, it won't be included in future glpi-agent versions.

**Comment by venator42** [comment]
Hi @g-bougard 

I have tested the file you gave me. Unfortunately it does not work.

For testing I installed the glpi-agent via the perl script: `perl glpi-agent-1.12-linux-installer.pl --type=all` and copied the file to `/usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/Snom.pm`. Is this correct so far?

 How can I test if it works? Executing `glpi-netdiscovery --debug --host 192.168.100.41` ? This returns:
```
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with netbios: no result
[debug] #1, - scanning 192.168.100.41 with echo ping: success
[debug] #1, - scanning 192.168.100.41 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated

```

I also created a task in GLPI Inventory Plugin with "Module method: Network discovery". Executing this job created unmanaged assets again or rather updates already created unmanaged assets.

**Comment by g-bougard** [comment]
Hi @venator42 

can you share the output where running with one more `--debug` to enable debug2 level ? `glpi-netdiscovery --debug --debug --host 192.168.100.41`

> missing response from host 192.168.100.41

But here you still have a message telling you the device didn't answer to SNMP request. You have to fix that before telling it doesn't work.

**Comment by venator42** [comment]
```
[debug2] /etc/glpi-agent/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with netbios: no result
[debug] #1, - scanning 192.168.100.41 with echo ping: success
[debug2] #1, executing arp -a 192.168.100.41
[debug] #1, - scanning 192.168.100.41 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```

SNMP is configured on the phone. The port is set to 161 and allowed adresses is set to my whole LAN for testing purposes. 

The command `snmpget -v1 -c public 192.168.100.41 1.3.6.1.2.1.7526.2.4` returns
```
SNMPv2-SMI::mib-2.7526.2.4 = STRING: "snomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)"
```

So SNMP is basically working.

**Comment by g-bougard** [comment]
So can you explain why in your first post I see:
```
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: success
```

And now I see:
```
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
```

This is an evidence of that agent doesn't have access to that SNOM on UDP port 161. Maybe a firewall issue you missed ?

**Comment by venator42** [comment]
This happens when I use the walkfile which I created (I don't know why it says success but doesnt show any information/data)

```
root@testpc:~# cat /tmp/snom-snmpwalk 
1.3.6.1.2.1.7526.2.4 = STRING: "Firmware"
root@testpc:~# glpi-netdiscovery --host 192.168.100.41 --debug --debug --v1 --community public --file /tmp/snom-snmpwalk
[debug2] /etc/glpi-agent/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: success
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
root@testpc:~# glpi-netdiscovery --host 192.168.100.41 --debug --debug --v1 --community public 
[debug2] /etc/glpi-agent/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with netbios: no result
[debug] #1, - scanning 192.168.100.41 with echo ping: success
[debug2] #1, executing arp -a 192.168.100.41
[debug] #1, - scanning 192.168.100.41 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
root@testpc:~# snmpget -v1 -c public 192.168.100.41 1.3.6.1.2.1.7526.2.6
SNMPv2-SMI::mib-2.7526.2.6 = INTEGER: 56
root@testpc:~# snmpget -v1 -c public 192.168.100.41 1.3.6.1.2.1.7526.2.4
SNMPv2-SMI::mib-2.7526.2.4 = STRING: "snomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)"
```

**Comment by g-bougard** [comment]
Glpi-agent relies on standard SNMP OIDs access. If your SNOM device doesn't provide them, glpi-agent can't manage it as expected.

So can you provide a full snmpwalk using the command you'll find here: https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output ?
Sorry, I should have started by requesting that file.

**Comment by venator42** [comment]
Unfortunately snmpwalk is not working. This is what i meant with 

> Unfortunately the phones only support SNMP-GET, so snmpwalk isn't working.

in my initial post. On their webseite snom is saying:

> Reading Information
The phone only supports the GET request of SNMP. SET or other requests are not supported. 


```
snmpwalk -v 1 -c public -t 15 -Cc -On -Ox 192.168.100.41 .1
Timeout: No Response from 192.168.100.41
```
This is also the reason I tried to create the walkfile manually, but this doesn't work either as you saw in my command output.

Does that mean, it is not possible to automatically inventory these phones?

**Comment by g-bougard** [comment]
From snmpwalk man page:
> snmpwalk is an SNMP application that uses SNMP GETNEXT requests to query a network entity for a tree of information.

So if GETNEXT requests are not supported, I understand snmpwalk is simply failing. I'm curious also to know if a device configuration can disable that limitation.

Actually, glpi-agent uses a mix of GET, GETNEXT & GETBULK requests. So it is not impossible to inventory these phones. But this makes its support development far more complex. A walk is convenient as it reports all GET-able OIDs. With manufacturer MIBs, it permits to easily identify datas we can effectively request to generate the expected inventory. As I can't count on a walk to simplify the development process, do you have more detailed documentation or official doc references on all available OIDs for these phones ?

**Comment by venator42** [comment]
I don't think there is a MIB provided by the manufacturer, at least I couldn't find any. All GET-table OIDs seems to be those on their website.

I found this gist: https://gist.github.com/indigo423/4a7f81dd39aa3269e462b2e4129fba6c

If you look at the last comment it looks like the implementation of SNMP of these phones is pretty poor.

**Comment by g-bougard** [comment]
Indeed I finally see my mistake... Snom uses `1.3.6.1.2.1.7526` so under `1.3.6.1.2.1` public and standardized where they should have use `1.3.6.1.4.1.7526` under `1.3.6.1.4.1` under private tree. This is totally a BIG mistake from Snom as `1.3.6.1.2.1.7526` is not standardized. My mistake was to look under the private tree...

Can you try the following module where I fixed the OID ?
[Snom-v2.zip](https://github.com/user-attachments/files/19211729/Snom-v2.zip)

**Comment by venator42** [comment]
I wish I had good news but it doesn't work. :/

Neither `1.3.6.1.2.1.7526` nor `1.3.6.1.4.1.7526` work. Actually `1.3.6.1.2.1.7526` is working, but only with snmpget. 

I found [this website](https://oidref.com/1.3.6.1.4.1.7526) where it says `.4` like you said. But the phone only responds to `.2` so I dont know why/how `.4` should work. 

Anyway, I still get `missing response from host` by glpi-netdiscovery command. 

While testing I got an additional message in the debug output: `PrivateOID match: snom mib support enabled`

```
root@testpc:/usr/share/glpi-agent# grep constant lib/GLPI/Agent/SNMP/MibSupport/Snom.pm 
use constant snom       => '.1.3.6.1.4.1.7526';
use constant firmware   => snom . '.2.4';
root@testpc:/usr/share/glpi-agent# cat /tmp/snom-snmpwalk 
.1.3.6.1.4.1.7526.2.4 = STRING: "Firmware & U-Boot Version"
root@testpc:/usr/share/glpi-agent# glpi-netdiscovery --host 192.168.100.41 --debug --debug --file /tmp/snom-snmpwalk 
[debug2] /etc/glpi-agent/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, PrivateOID match: snom mib support enabled
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: success
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```
As before, no results.

**Comment by g-bougard** [comment]
Hi @venator42 

2 days ago you said:
> The command `snmpget -v1 -c public 192.168.100.41 1.3.6.1.2.1.7526.2.4` returns
> ```
> SNMPv2-SMI::mib-2.7526.2.4 = STRING: "snomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)"
> ```
> So SNMP is basically working.

And this is the OID we can see in the gist you referenced yesterday.

So `1.3.6.1.2.1.7526.2.4` seems to work for Snom phones. This is the big change I made between my v1 & my v2.

Your grep in your last comment shows you're using v1 which I said is wrong: `use constant snom       => '.1.3.6.1.4.1.7526';` is changed to `use constant snom       => '.1.3.6.1.2.1.7526';` in my v2.

Also your pseudo-walk is wrong, you set the wrong OID. Did you try ``snmpget -v1 -c public 192.168.100.41 1.3.6.1.4.1.7526.2.4` ?

Other point: `glpi-netdiscovery --host 192.168.100.41 --debug --debug --file /tmp/snom-snmpwalk` uses only your walk, if it is wrong as I suspect, don't use it and directly test the v2 on your Snom phone with `glpi-netdiscovery --host 192.168.100.41 --debug --debug`.

**Comment by venator42** [comment]
I only used `.1.3.6.1.4.1.7526` because it is in both files from you, even v2.

My last example with the pseudo-walk doesn't work with `.1.3.6.1.2.1.7526` neither. I switched back and forth to test and my last post had `.4` in it.

As of now, I'm using your you v2 and changed `use constant snom       => '.1.3.6.1.4.1.7526'` to `use constant snom       => '.1.3.6.1.2.1.7526'`

```
root@testpc:/usr/share/glpi-agent# grep constant lib/GLPI/Agent/SNMP/MibSupport/Snom.pm 
use constant snom       => '.1.3.6.1.2.1.7526';
use constant firmware   => snom . '.2.4';
root@testpc:/usr/share/glpi-agent# glpi-netdiscovery --host 192.168.100.41 --debug --debug
[debug2] /etc/glpi-agent/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: no result, missing response from host 192.168.100.41
[debug] #1, - scanning 192.168.100.41 with netbios: no result
[debug] #1, - scanning 192.168.100.41 with echo ping: success
[debug2] #1, executing arp -a 192.168.100.41
[debug] #1, - scanning 192.168.100.41 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```

**Comment by g-bougard** [comment]
Argh, I failed to upload the right module version, sorry sorry...

So let's try the v3:

[Snom-v3.zip](https://github.com/user-attachments/files/19230210/Snom-v3.zip)

**Comment by venator42** [comment]
Tried it out but doesn' work. 

I then fired up wireshark trying to find out what actually happens there low level.

The agent PC sends a `get-request 1.3.6.1.2.1.1.1.0`. The phone sends a `get response` (without OID). In addition I have an entry with NBNS protocol from my agent PC to the phone and one ICMP Package from the phone to my agent PC which says `Destination unreachable (Port unrechable)`. Both devices are definitely on the same subnet and can reach each other. I even tried with my PC on the same subnet, didnt help.

If I execute `glpi-netdiscovery` on a printer it works fine (there is no ICMP package e.g.) The difference is that the first `get-response` also includes the OID. So I got something like 
```
Agent -> Printer : get-request 1.3.6.1.2.1.1.1.0
Printer -> Agent: get-response 1.3.6.1.2.1.1.1.0
```
whereas between Agent and phone it looks like this:
```
Agent -> Phone : get-request 1.3.6.1.2.1.1.1.0
Phone -> Agent: get-response 
```

I tested with different devices like printer, switches etc. These devices are responding to the system description OID `1.3.6.1.2.1.1.1.0`. The snom phones don't respond to that OID. Could that be the culprit?

**Comment by g-bougard** [comment]
Hi @venator42 

is this the only snmp request glpi-agent is doing on your phone or is there any other ones ? If you want, you can share the network traffic dump on UDP port 161 between agent and the phone. Maybe I'll see something interesting.

In theory, having an answer on `.1.3.6.1.2.1.1.1.0` is not a condition. And the module I proposed attempts to compensate the missing of this OID.

**Comment by venator42** [comment]
Hi @g-bougard 

yes, this is the only traffic between phone and agent. 

[snom_snmp_capture.txt](https://github.com/user-attachments/files/19246084/snom_snmp_capture.txt) (I censored a bit like pc IP address or MAC addresses)

I hope I imported the `Snom.pm` file correctly. Do I need to do anything after copying it into the directory? Like restarting `glpi-agent.service` in systemd? I actually tried that but maybe I missed something else.

**Comment by g-bougard** [comment]
Well, I better expected the capture file itself so I can analyze it myself in my own Wireshark session (or tcpdump command if capture file is still compatible).

Can you eventually send it to me by email at `gbougard <at> teclib <dot> com` ?
To be complete, I would expect you to start a UDP port 161 capture session on the same computer than the one running glpi-netdiscovery command. Only that UDP port is interesting. And I would also expect you share the output of `glpi-netdiscovery --host 192.168.100.41 --debug --debug` you run at the same time, to see how glpi-agent handles the response and to know if the module I provided was used.

To be honest, I'm still not convinced every thing is running as expected. You should not see only one SNMP request passing, or I really missed a big point somewhere. Some other MibSupport modules should try other private OIDs and it seems not the case with your explanations.

**Comment by g-bougard** [comment]
Well, forget it, I missed a point: the only request you're seeing is coming from here: https://github.com/glpi-project/glpi-agent/blob/255f8d3f1f6f401695fb1cb2e17fcfaf8a97ad8d/lib/GLPI/Agent/SNMP/Live.pm#L67

GLPI-Agent always tries to get 1.3.6.1.2.1.1.1.0 to open and validate a SNMP session.

So actually this will always fail.

The change to support wrongly designed SNMP support from SNOM phones is finally more complex than I expected.

**Comment by g-bougard** [comment]
So can you try by updating SNMP/Live.pm with the following version ?
[Snmp-Live.zip](https://github.com/user-attachments/files/19249679/Snmp-Live.zip)

I applied the following patch on it:
```diff
index c76bb1d22..1b4f1b08e 100644
--- a/lib/GLPI/Agent/SNMP/Live.pm
+++ b/lib/GLPI/Agent/SNMP/Live.pm
@@ -63,10 +63,13 @@ sub new {
     }
 
     if ($version ne 'snmpv3') {
-        my $oid = '.1.3.6.1.2.1.1.1.0';
-        my $response = $self->{session}->get_request(
-            -varbindlist => [$oid]
-        );
+        my ($oid, $response);
+        foreach $oid (qw(.1.3.6.1.2.1.1.1.0 .1.3.6.1.2.1.7526.2.4)) {
+            $response = $self->{session}->get_request(
+                -varbindlist => [$oid]
+            );
+            last if $response;
+        }
         die "no response from host $params{hostname}\n"
             if !$response;
         die "missing response from host $params{hostname}\n"
```

**Comment by venator42** [comment]
Hi @g-bougard ,

It tested the modified `Live.pm` but it didn't worked for me. The output was basically the same but there was one additional line:
```
Use of uninitialized value $oid in hash element at lib/GLPI/Agent/SNMP/Live.pm line 76.
```

For testing purposes I reverted to the original file and changed the OID and that worked. But I got no firmware or model. I edited regex in `Snom.pm`. You can take a look at my modifications here: [Snom-Snmp.zip](https://github.com/user-attachments/files/19282575/Snom-Snmp.zip) I also included the output of tcpdump on UDP Port 161.

Although this is somewhat working, I got a bunch of these in the output of `glpi-netdiscovery`:
```
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
```

I also had to use `--timeout 1`. Otherwise the command takes 7 minutes.

<details>

<summary>Full output</summary>

```
[debug2] /home/xx/Downloads/GLPI-Agent-1.12/etc/toolbox.yaml configuration not found
[debug] initializing job 1
[debug] initializing block 192.168.100.41-192.168.100.41
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 192.168.100.41
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
[debug] #1, PrivateOID match: snom mib support enabled
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 144.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 145.
Use of uninitialized value in pattern match (m//) at lib/GLPI/Agent/SNMP/Live.pm line 146.
[debug] #1, - scanning 192.168.100.41 with SNMP, credentials 1: success
[debug] #1, - scanning 192.168.100.41 with netbios: no result
[debug] #1, - scanning 192.168.100.41 with echo ping: success
[debug2] #1, executing arp -a 192.168.100.41
[debug] #1, - scanning 192.168.100.41 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <FIRMWARE>snomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)</FIRMWARE>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
      <MANUFACTURER>Snom</MANUFACTURER>
      <MODEL>snomD385</MODEL>
      <TYPE>NETWORKING</TYPE>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated

real    7m3,198s
user    0m0,007s
sys     0m0,000s
```

</details>

The XML Output looks like this now:
```
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <FIRMWARE>snomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)</FIRMWARE>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
      <MANUFACTURER>Snom</MANUFACTURER>
      <MODEL>snomD385</MODEL>
      <TYPE>NETWORKING</TYPE>
    </DEVICE>
    <MODULEVERSION>6.5</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

**Comment by g-bougard** [comment]
Hi @venator42 

thank you for this feedback.

I dig a little further and I possibly found a good way to help Snom phones support.

I still added a GLPI-Agent core update yesterday to simplify the way to load dedicated configuration file. This feature is used by HTTP server plugins for example.

Anyway, can you update your agent to the current nightly ? https://nightly.glpi-project.org/glpi-agent/
Then extract the 3 files from the following archive other your installation: [Snom-Support-v4.zip](https://github.com/user-attachments/files/19316420/Snom-Support-v4.zip)
It contains an update of SNMP::Live module and update of NetDiscovery and NetInventory tasks to follow that SNMP::Live update.


With just that, you still won't be able to inventory Snom phones. Indeed, you may still miss the dedicated Snom module from [Snom-v3.zip](https://github.com/user-attachments/files/19230210/Snom-v3.zip), take it again if the glpi-agent update remove it.

Then create a new configuration file next to the default "agent.cfg" one: `/etc/glpi-agent/snmp-live.cfg`
And just add one line to define "oids" value as follow:
```
oids = .1.3.6.1.2.1.1.1.0,.1.3.6.1.2.1.7526.2.4
```
Then run tests again. This should be far better.

With this update and dedicated configuration, glpi-agent when testing snmp session will send a snmp requet on each listed oid. If at least one respond, the session will be validated.

**Comment by venator42** [comment]
Hi,

I tested the nightly agent on two different agents and it works so far except for two things:

- The regular expressions in `MibSupport/Snom.pm` needs to be fixed because they don't return anything. In [my last comment](#issuecomment-2728679592) I uploaded an example in the .zip which worked for me.
- Without `--timeout 1` it takes very long to finish. Today it took even longer than yesterday (9 minutes today). I think this is caused by SNMP requests waiting for a timeout because they don't get an answer.

I will send you an e-mail with a pcap file to the mail address you mentioned in [your previous comment](#issuecomment-2724888688)

**Comment by g-bougard** [comment]
Thank you for the pcap file, I was able to directly saw the problem for the long delay: each time glpi-agent send a GET-NEXT-REQUEST it fails on the default timeout which is 60 seconds.

Glpi-agent makes GET-NEXT-REQUEST when it wants to walk an oid tree. This is required in many place for switchs inventory or printers for example. As you told before, GET-NEXT-REQUEST are not supported by Snom phones. And this should be definitively banned when analyzing a Snom phone.

So I included another fix to disable walk support:
[Snom-Support-v5.zip](https://github.com/user-attachments/files/19322842/Snom-Support-v5.zip)

This archive contains same files than v4. They were not modified. But it also includes SNMP/Device.pm which support disableWalk() API. Included Snom.pm module now calls that API to disable walks an so unsupported requests.
To follow your last comment, I also updated Snom module to extract model and firmware, but this time using a split command. I also included uboot firmware version extraction.

You only need to install lib/GLPI/Agent/SNMP/Device.pm & lib/GLPI/Agent/SNMP/MibSupport/Snom.pm from v5 other v4.

**Comment by venator42** [comment]
It's a bit faster but there are still some GetNextRequest.
```
GetNextRequest(29)  .1.3.6.1.2.1.1.9.1.2
GetNextRequest(31)  .1.3.6.1.2.1.47.1.1.1.1.13
GetNextRequest(31)  .1.3.6.1.2.1.47.1.1.1.1.11
GetNextRequest(30)  .1.3.6.1.2.1.43.5.1.1.17
```
Firmware now returns:
```
<FIRMWARE>nomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)</FIRMWARE>
```

Full output:
```
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <FIRMWARE>nomD385-SIP 10.1.184.14 2010.12-00001-gd311851f1 (Feb 25 2019 - 14:17:02)</FIRMWARE>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
      <MANUFACTURER>Snom</MANUFACTURER>
      <TYPE>NETWORKING</TYPE>
    </DEVICE>
    <MODULEVERSION>6.6</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

**Comment by g-bougard** [comment]
Okay,

sorry, I made 2 typos in Snom.pm.

For the duration, I forgot Tools/Hardware.pm also makes a lot of walk call. I had to refacto it too and adapt Device module too to follow this refacto.

So here is another archive: [Snom-Support-v6.zip](https://github.com/user-attachments/files/19340158/Snom-Support-v6.zip)

From it, you only need to update `lib/GLPI/Agent/SNMP/Device.pm`, `lib/GLPI/Agent/SNMP/MibSupport/Snom.pm` and the new one: `lib/GLPI/Agent/Tools/Hardware.pm`

**Comment by venator42** [comment]
This is looking pretty good now. 
```
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DNSHOSTNAME>192.168.100.41</DNSHOSTNAME>
      <FIRMWARE>10.1.184.14</FIRMWARE>
      <IP>192.168.100.41</IP>
      <MAC>00:04:13:93:03:ac</MAC>
      <MANUFACTURER>Snom</MANUFACTURER>
      <MODEL>snomD385-SIP</MODEL>
      <TYPE>NETWORKING</TYPE>
    </DEVICE>
    <MODULEVERSION>6.6</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

There is still one GetNextRequest left: `GetNextRequest(29)  .1.3.6.1.2.1.1.9.1.2`.

```
GLPI-Agent-1.14-git1310a2ba$ grep -r "1.3.6.1.2.1.1.9.1.2"
lib/GLPI/Agent/SNMP/MibSupport.pm:use constant    sysORID => '.1.3.6.1.2.1.1.9.1.2';
lib/GLPI/Agent/SNMP/Mock.pm:    'SNMPv2-MIB::sysORID'               => '.1.3.6.1.2.1.1.9.1.2',
```

**Comment by g-bougard** [comment]
Yes, this one I won't be able to disable it: it happens during the MibSupport modules loading and so before Snom module is loaded.

Keep timeout set to 1 and this means you'll only loose 1 second on Snom phone. That's not a big deal from my point of view.

Have you also tried to run netinventory ? It should also provide uboot firmware. In GLPI, you have to enable update & import by MAC rules.

**Comment by venator42** [comment]
Ok, I can totally live with 1 second timeout.

This is the output of `glpi-netinventory`:
```
<REQUEST>
  <CONTENT>
    <DEVICE>
      <FIRMWARES>
        <DESCRIPTION>device firmware</DESCRIPTION>
        <MANUFACTURER>Snom</MANUFACTURER>
        <NAME>snomD385-SIP</NAME>
        <TYPE>device</TYPE>
        <VERSION>10.1.184.14</VERSION>
      </FIRMWARES>
      <FIRMWARES>
        <DESCRIPTION>Snom Uboot firmware</DESCRIPTION>
        <MANUFACTURER>Snom</MANUFACTURER>
        <NAME>Snom Uboot version</NAME>
        <TYPE>system</TYPE>
        <VERSION>2010.12-00001-gd311851f1</VERSION>
      </FIRMWARES>
      <INFO>
        <FIRMWARE>10.1.184.14</FIRMWARE>
        <ID>0</ID>
        <MANUFACTURER>Snom</MANUFACTURER>
        <MODEL>snomD385-SIP</MODEL>
        <TYPE>NETWORKING</TYPE>
      </INFO>
    </DEVICE>
    <MODULEVERSION>6.6</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

How does the import in GLPI work from now on? The MAC Rules are enabled. I created two tasks under `Administration - GLPI Inventory - Task management` (one for discovery and one for Network Inventory (SNMP)). If I want to execute the network inventory task, nothing really happens even when I click "Force Start". The discovery task executes but imports the phone as unmanaged asset.

Edit: It worked! I forgot to link the SNMP credentials with the IP Range I created for this single phone.

**Comment by g-bougard** [comment]
So here we go, we have Snom phones support or something is missing/wrong ?

I can merge the proposed code. I'll probably change the dedicated configuration filename to something else as it could be used for other purpose in the future. I choose a quick name during the dev. I'll probably use a name like "snmp-advanced-features.cfg".

**Comment by venator42** [comment]
I don't think the other values like received bytes or status of registration makes sense regarding to inventory, therefore nothing is missing.

Cherry on top would be if its possible to import as phone, but you said it not really possible. I can accept the import as network device though, it's really good that they get imported at all now.

**Comment by g-bougard** [comment]
> Cherry on top would be if its possible to import as phone, but you said it not really possible. I can accept the import as network device though, it's really good that they get imported at all now.

Fyi, this will be possible in GLPI 11+. A beta will be released soon, maybe you'll want to test it and your feedback would be appreciated.

**Comment by venator42** [comment]
That's nice to hear. I will check it out.

**Comment by g-bougard** [comment]
Hi @venator42 

I just pushed the code. You'll be able to use next nightly build. But I made a change, I renamed the `snmp-live.cfg` file to `snmp-advanced-support.cfg`. It contains an example for your case, but it also contains a "include" directive to load `snmp-advanced-support.local`. So you should create your own config as `snmp-advanced-support.local`.

Thank you again for the shared datas.

**Comment by venator42** [comment]
Hi @g-bougard 

thank you too for implementing this!

**Comment by JonasM49** [comment]
@g-bougard Snom support is very interesting.

I tried the nightly build GLPI-Agent v1.14-gite7e0b7a0 on a server, but get the following error:
```
Subroutine new redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 17.
Subroutine getType redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 26.
Subroutine getManufacturer redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 29.
Subroutine getModel redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 32.
Subroutine getFirmware redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 39.
Subroutine run redefined at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport/snom.pm line 46.
Can't locate object method "configure" via package "GLPI::Agent::SNMP::MibSupport::snom" (perhaps you forgot to load "GLPI::Agent::SNMP::MibSupport::snom"?) at /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport.pm line 127
```

**Comment by g-bougard** [comment]
Hi @JonasM49 

You have this error because you have a `snom.pm` file which is definitively not part of GLPI-Agent. That name is fully in lower case which is not the case in GLPI-Agent. Don't you have a `Snom.pm` file just next this `snom.pm` file ? My guess is you tried to install the file provided in this issue but wrongly seeting the filename case but this is not needed as it is now provided in nightly builds.

**Comment by JonasM49** [comment]
@g-bougard 
My fault, before I added a file in lower case manually and installed the nightly build with the correct file.

After deleting the wrong file, it works for me.

snmpget -v1 -c public 10.91.x.x:161 1.3.6.1.2.1.47.1.1.1.1.11
this get's the MAC adress of the device to identify it, this is missing up to now

**Comment by geel97** [comment]
Hi.
I just uncommented the line `oids = .1.3.6.1.2.1.1.1.0,.1.3.6.1.2.1.7526.2.4` in `glpi-agent/snmp-advanced-support.cfg` but the devices stays in Unmanaged asset in GLPI. Do I miss something?
This is the output of `glpi-netinventory --host 10.12.1.17`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <FIRMWARES>
        <DESCRIPTION>device firmware</DESCRIPTION>
        <MANUFACTURER>Snom</MANUFACTURER>
        <NAME>snom715-SIP</NAME>
        <TYPE>device</TYPE>
        <VERSION>8.9.3.80</VERSION>
      </FIRMWARES>
      <FIRMWARES>
        <DESCRIPTION>Snom Uboot firmware</DESCRIPTION>
        <MANUFACTURER>Snom</MANUFACTURER>
        <NAME>Snom Uboot version</NAME>
        <TYPE>system</TYPE>
        <VERSION>2010.12-00003-g3143800</VERSION>
      </FIRMWARES>
      <INFO>
        <FIRMWARE>8.9.3.80</FIRMWARE>
        <ID>0</ID>
        <MANUFACTURER>Snom</MANUFACTURER>
        <MODEL>snom715-SIP</MODEL>
        <TYPE>NETWORKING</TYPE>
      </INFO>
    </DEVICE>
    <MODULEVERSION>6.8</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

**Comment by g-bougard** [comment]
Hi @geel97 

IP & MACADDR in the INFO section are missing. You may need to run the script as next as possible than the device from the network point of view.

Also, you'll have to enable import and update by MAC rules.

**Comment by geel97** [comment]
Hi @g-bougard 
My agent is not on the same voip network, are different VLANs. You mean that is mandatory to have the agent on the same network?

**Comment by g-bougard** [comment]
This is only required when we can't discover MAC address via SNMP: in that case, we can only know remote MAC address via local arp table. In that last case, you need to have glpi-agent in the same physical network than devices.

**Comment by geel97** [comment]
Ok, I understand. I will work to solve that issue on our side. Thanks a lot!

**Comment by andreaPress** [comment]
Hi, first of all thank you for the information shared in this thread and for the great work you’re doing on GLPI as an open-source project.

I tried to follow what is described in this thread, but I’m facing an issue when trying to classify Snom phones correctly.

Here is my setup:

* I have a GLPI Agent installed on an Ubuntu server in the same VLAN as Snom D715/D717 phones.
* I allowed the IP address of the agent host in the phone provisioning, so the devices respond to SNMP queries.
* I created the following file:

```
/etc/glpi-agent/snmp-advanced-support.local
```

with:

```
# SNOM IP Phones
oids = .1.3.6.1.2.1.1.1.0,.1.3.6.1.2.1.7526.2.4
```

(as described in the agent documentation, page 39) [https://glpi-agent.readthedocs.io/_/downloads/en/latest/pdf/](https://glpi-agent.readthedocs.io/_/downloads/en/latest/pdf/)

* Here is an example of the discovery result:

```
sudo glpi-netdiscovery --host 10.220.1.220 --credentials version:1,community:public --debug
```

The relevant part of the output is:

```xml
[info] Can't load GLPI::Agent::IEC61850::Device, iec61850 devices detection can't be used
[info] Can't load iec61850 perl library, iec61850 devices detection won't be used
[debug] initializing job 1
[debug] initializing block 10.220.1.220-10.220.1.220
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 10.220.1.220
[debug] #1, PrivateOID match: snom mib support enabled
[debug] #1, - scanning 10.220.1.220 with SNMP, credentials 1: success
[debug] #1, - scanning 10.220.1.220 with netbios: no result
[debug] #1, - scanning 10.220.1.220 with echo ping: success
[debug] #1, - scanning 10.220.1.220 in arp table: success
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DNSHOSTNAME>10.220.1.220</DNSHOSTNAME>
      <FIRMWARE>10.1.215.13</FIRMWARE>
      <IP>10.220.1.220</IP>
      <IPS>
        <IP>10.220.1.220</IP>
      </IPS>
      <MAC>00:04:13:XX:XX:XX</MAC>
      <MANUFACTURER>Snom</MANUFACTURER>
      <MODEL>snom715-SIP</MODEL>
      <TYPE>NETWORKING</TYPE>
    </DEVICE>
    <MODULEVERSION>7.0</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```

* I created two rules (import and update) based on MAC address.

<img width="2618" height="276" alt="Image" src="https://github.com/user-attachments/assets/941541f8-046a-49c3-9362-7ef3710d40c8" />

In my rules, using “MAC address starts with 00:04:13” allows me to correctly identify all my Snom phones, since the first part of the MAC address is always the same.
Up to this point everything works correctly:
the agent retrieves the MAC address and the device is imported as a network device.

---

## The issue

To classify the device as a **phone**, I created an additional rule using “Transform itemtypes”.

<img width="2218" height="122" alt="Image" src="https://github.com/user-attachments/assets/d00380f0-6a00-4517-9e1c-bb548c06398d" />

However, when I enable this rule:

* after the agent runs an inventory,
* the server where the agent is installed is incorrectly transformed from **Computer** to **Phone**,
* and the agent stops working properly.

In GLPI:

* the server still appears under Computers,
* but in the agent view, the itemtype becomes “Phone”,
* and agent-related information is no longer available.

---

## My understanding

It seems that the “Transform itemtypes” rule is applied too early in the processing pipeline (before proper distinction between agent inventory and SNMP devices), and it also affects the agent host itself.

---

## Question
Since I find extremely useful the association between computers and network devices through switch ports (where often the PC is connected behind the phone), it would be great to also have visibility into the phone itself through SNMP integration with Snom devices.

Am I missing a condition to properly limit this rule only to SNMP-discovered devices?

Any suggestion on the correct way to classify Snom phones as “Phones” without affecting agent-based computers would be greatly appreciated.

Thanks a lot for your help!
