### ISSUE TITLE
Linux machines are no longer updated

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/glpi-agent#992]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

We have a handful of Linux machines that are no longer being updated via inventory run.
One particular machine not for over a month.

When investigating the `sql-errors.log` the agent sends `other` to the database rather than `4` (which is the numeric value for `Other`)

```
[2025-08-04 11:10:29] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 395
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computers` (`autoupdatesystems_id`, `last_inventory_update`, `is_deleted`, `name`, `computertypes_id`, `manufacturers_id`, `computermodels_id`, `is_dynamic`, `entities_id`, `states_id`, `date_creation`, `date_mod`) VALUES ('1', '2025-08-04 11:10:29', '0', 'ws', '2', '152', 'Super Server', '1', '1', '1', '2025-08-04 11:10:29', '2025-08-04 11:10:29')
  Error: Incorrect integer value: 'Super Server' for column `glpi`.`glpi_computers`.`computermodels_id` at row 1
  Backtrace :
  src/DBmysql.php:1377                               DBmysql->doQuery()
  src/CommonDBTM.php:726                             DBmysql->insert()
  src/CommonDBTM.php:1345                            CommonDBTM->addToDB()
  src/Inventory/Asset/MainAsset.php:722              CommonDBTM->add()
  src/RuleImportAsset.php:1004                       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1537                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1658                        Rule->process()
  src/Inventory/Asset/MainAsset.php:581              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:727                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:358                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:381                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:100                            Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  public/index.php:82                                require()
  {"user":"inventory@glpi"} 
```

In another instance the computer model is send rather than the numeric value for the model:

```
[2025-08-04 11:10:29] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 395
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computers` (`autoupdatesystems_id`, `last_inventory_update`, `is_deleted`, `name`, `computertypes_id`, `manufacturers_id`, `computermodels_id`, `is_dynamic`, `entities_id`, `states_id`, `date_creation`, `date_mod`) VALUES ('1', '2025-08-04 11:10:29', '0', 'ws', '2', '152', 'Super Server', '1', '1', '1', '2025-08-04 11:10:29', '2025-08-04 11:10:29')
  Error: Incorrect integer value: 'Super Server' for column `glpi`.`glpi_computers`.`computermodels_id` at row 1
  Backtrace :
  src/DBmysql.php:1377                               DBmysql->doQuery()
  src/CommonDBTM.php:726                             DBmysql->insert()
  src/CommonDBTM.php:1345                            CommonDBTM->addToDB()
  src/Inventory/Asset/MainAsset.php:722              CommonDBTM->add()
  src/RuleImportAsset.php:1004                       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1537                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1658                        Rule->process()
  src/Inventory/Asset/MainAsset.php:581              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:727                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:358                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:381                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:100                            Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  public/index.php:82                                require()
  {"user":"inventory@glpi"} 
```

### To reproduce

Would not know how to replicate.

### Expected behavior

The inventory should be updated once every 24 hours.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (Details in additional context below)

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.5.3

### Additional context

GLPI Version 10.0.19
GLPI-Agent_v1.16-git6419c7c7

**Comment by GuidoWilden** [comment]
Just reproduced the problem with agent 1.15.

**Comment by Mirkk** [comment]
Hi @GuidoWilden I had this same issue when some items (e.g. operating system) were locked. However this should be solved in 10.0.19.

**Comment by GuidoWilden** [comment]
Thank you @Mirkk, I just cleared all locks from one of the machines (at least the ones I could clear. Weirdly there is a long list of locks I can't clear. Not something I have seen before) and still no luck.

<img width="1150" height="808" alt="Image" src="https://github.com/user-attachments/assets/3d0f1cae-e9e4-493c-894c-6e7832049f55" />

**Comment by g-bougard** [comment]
Hi @GuidoWilden 

To me this is a server issue and you should report it on GLPI GH issues.

**Comment by GuidoWilden** [comment]
Thank you @g-bougard, I will maybe try.
